### PR TITLE
OCPBUGS-1272: Add pipe support to render-veneer basic command (#1026)

### PR DESCRIPTION
**Pull request by oceanc80**
Signed-off-by: Catherine Chan-Tse <cchantse@redhat.com>
Upstream-repository: operator-registry
Upstream-commit: 614d6a955dc0d7d341dfa71215b373bf401864c3

### CODE REVIEW

**Comment by tylerslaton** [comment]
Do make this bug valid and linked do we need to see the `Fix Version(s)` in Jira?

**Comment by tylerslaton** [comment]
@oceanc80 Looks like verify is failing because your commit message is slightly off.

**Comment by Xia-Zhao-rh** [comment]
/label qe-approved 

```
zhaoxia@xzha-mac OCP-53869 % opm-401 version
Version: version.Version{OpmVersion:"5c21ea579", GitCommit:"5c21ea579401736368856b727c904d32838f8be6", BuildDate:"2022-10-11T01:10:05Z", GoOs:"darwin", GoArch:"amd64"}

zhaoxia@xzha-mac OCP-53869 % opm-401 alpha render-veneer         
Render a veneer type


Usage:
  opm alpha render-veneer [command]


Available Commands:
  basic       Generate a file-based catalog from a single 'basic veneer' file
When FILE is '-' or not provided, the veneer is read from standard input
  semver      Generate a file-based catalog from a single 'semver veneer' file
When FILE is '-' or not provided, the veneer is read from standard input


Flags:
  -h, --help   help for render-veneer


Global Flags:
      --skip-tls-verify   skip TLS certificate verification for container image registries while pulling bundles
      --use-http          use plain HTTP for container image registries while pulling bundles


Use "opm alpha render-veneer [command] --help" for more information about a command. 

zhaoxia@xzha-mac OCP-53869 % opm-401 alpha render-veneer basic -h
Generate a file-based catalog from a single 'basic veneer' file
When FILE is '-' or not provided, the veneer is read from standard input


Usage:
  opm alpha render-veneer basic basic-veneer-file [flags]


Flags:
  -h, --help            help for basic
  -o, --output string   Output format (json|yaml) (default "json")


Global Flags:
      --skip-tls-verify   skip TLS certificate verification for container image registries while pulling bundles
      --use-http          use plain HTTP for container image registries while pulling bundles

zhaoxia@xzha-mac OCP-53869 % cat catalog-basic-veneer.yaml 
---
schema: olm.package
name: nginx-operator
defaultChannel: stable
---
schema: olm.channel
package: nginx-operator
name: stable
entries:
- name: nginx-operator.v0.0.1
- name: nginx-operator.v1.0.1
  replaces: nginx-operator.v0.0.1
---
schema: olm.bundle
image: quay.io/olmqe/nginxolm-operator-bundle:v0.0.1
---
schema: olm.bundle
image: quay.io/olmqe/nginxolm-operator-bundle:v1.0.1

zhaoxia@xzha-mac OCP-53869 % cat catalog-basic-veneer.yaml | opm-401 alpha render-veneer basic -o yaml
---
defaultChannel: stable
name: nginx-operator
schema: olm.package
---
entries:
- name: nginx-operator.v0.0.1
- name: nginx-operator.v1.0.1
  replaces: nginx-operator.v0.0.1
name: stable
package: nginx-operator
schema: olm.channel
---
image: quay.io/olmqe/nginxolm-operator-bundle:v0.0.1
name: nginx-operator.v0.0.1
package: nginx-operator
properties:
- type: olm.gvk
  value:
    group: olm.example.com
    kind: NginxOLM
    version: v1alpha1
- type: olm.package
  value:
    packageName: nginx-operator
    version: 0.0.1
- type: olm.bundle.object
  value:
...
```

**Comment by tylerslaton** [comment]
Nice, this looks good! 

/unhold

**Review by timflannagan — APPROVED** [review]

**Comment by grokspawn** [comment]
/retest-required

kicking gcp again.  It's consistently failing, complaining about some deprecated resources, but this PR contains no expected e2e impacts.  It might just be timing.

**Comment by grokspawn** [comment]
/test e2e-gcp-olm

This looks like an unrelated flake, but just in case gonna kick it one more time.

**Pull request merged**
