### PR TITLE
Updown sync 2

### PR DESCRIPTION
**Pull request by perdasilva**
This PR brings down the latest changes from the upstream. The following fixes were applied on top:

1. A diff comparison between up and (post sync'ed) down showed a few differences. A commit was added to correct the drift.
2. There was a change required `values.yaml` to fix the opmImage flag to be passed with two dashes ("--opmImage")
3. A patch to the MagicCatalog was needed to fix the path to the resource file. This is a stopgap and a corresponding ticket was created on the upstream to try to address this issues. It is also documented in code.
4. Dropped Aki's PR that checks for operatorhubio catalog being up before the e2e tests start

### CODE REVIEW

**Comment by perdasilva** [comment]
retest ci/prow/e2e-aws-olm

**Comment by perdasilva** [comment]
I believe this PR is ready for merging, though we may need to override a couple of failing jobs.

`ci/prow/verify` is failing because this PR includes commits with changes to staging. This was required to fix the drift resulting from applying commits out of order, and to fix the MagicCatalog e2e tests

`ci/prow/e2e-aws-olm` is failing due to flakes:

### Operator API Tests
End-to-end: Operator API [FLAKE] should surface components in its status
End-to-end: Operator API when a subscription to a package exists should automatically adopt components

#### Local verification

```bash
$ make e2e WHAT=operator-lifecycle-manager E2E_INSTALL_NS=openshift-operator-lifecycle-manager E2E_TEST_NS=openshift-operators TEST="Operator API"

Ran 3 of 179 Specs in 199.628 seconds
SUCCESS! -- 3 Passed | 0 Failed | 0 Pending | 176 Skipped
```

### Catalog

End-to-end: Catalog represents a store of bundles which OLM can use to install Operators delete internal registry pod triggers recreation

```bash
make e2e WHAT=operator-lifecycle-manager E2E_INSTALL_NS=openshift-operator-lifecycle-manager E2E_TEST_NS=openshift-operators TEST="delete internal registry pod triggers recreation"                                                                                                                                                          9.1m  Fri 11 Mar 2022 09:28:00
scripts/e2e.sh
~/repos/perdasilva/operator-framework-olm/staging/operator-lifecycle-manager ~/repos/perdasilva/operator-framework-olm
Populating nested vendor directory
all modules verified
Running operator-lifecycle-manager e2e tests
make[1]: Entering directory '/home/perdasilva/repos/perdasilva/operator-framework-olm/staging/operator-lifecycle-manager'
GO111MODULE=on GOFLAGS="-mod=vendor" go run github.com/onsi/ginkgo/ginkgo   -focus 'delete internal registry pod triggers recreation' -flakeAttempts 1 -nodes 1 -timeout 90m -v -randomizeSuites -race -trace -progress ./test/e2e  -- -namespace=openshift-operators -olmNamespace=openshift-operator-lifecycle-manager -dummyImage=bitnami/nginx:latest -kubeconfig=/home/perdasilva/.crc/machines/crc/kubeconfig
Running Suite: End-to-end
=========================
Random Seed: 1646987301
Will run 1 of 179 specs

SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
------------------------------
Catalog represents a store of bundles which OLM can use to install Operators 
  delete internal registry pod triggers recreation
  /home/perdasilva/repos/perdasilva/operator-framework-olm/staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go:529
[BeforeEach] Catalog represents a store of bundles which OLM can use to install Operators
  /home/perdasilva/repos/perdasilva/operator-framework-olm/staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go:41
[It] delete internal registry pod triggers recreation
  /home/perdasilva/repos/perdasilva/operator-framework-olm/staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go:529
Creating catalog source catalog-cx4rd in namespace openshift-operators...
Catalog source catalog-cx4rd created
Waiting for pods matching selector olm.catalogSource=catalog-cx4rd to match given conditions
Waiting for pods matching selector olm.catalogSource=catalog-cx4rd to match given conditions
waiting for [5370f775-0fe1-41da-8c2a-716a6428a1ea] not to contain 5370f775-0fe1-41da-8c2a-716a6428a1ea
Waiting for pods matching selector olm.catalogSource=catalog-cx4rd to match given conditions
waiting for [5370f775-0fe1-41da-8c2a-716a6428a1ea] not to contain 5370f775-0fe1-41da-8c2a-716a6428a1ea
Waiting for pods matching selector olm.catalogSource=catalog-cx4rd to match given conditions
waiting for [5370f775-0fe1-41da-8c2a-716a6428a1ea] not to contain 5370f775-0fe1-41da-8c2a-716a6428a1ea
Waiting for pods matching selector olm.catalogSource=catalog-cx4rd to match given conditions
waiting for [5370f775-0fe1-41da-8c2a-716a6428a1ea] not to contain 5370f775-0fe1-41da-8c2a-716a6428a1ea
Waiting for pods matching selector olm.catalogSource=catalog-cx4rd to match given conditions
waiting for [5370f775-0fe1-41da-8c2a-716a6428a1ea] not to contain 5370f775-0fe1-41da-8c2a-716a6428a1ea
Waiting for pods matching selector olm.catalogSource=catalog-cx4rd to match given conditions
waiting for [f9df93a0-3195-4f63-8ff8-da7d01a5c5e0] to not be empty and not contain 5370f775-0fe1-41da-8c2a-716a6428a1ea
Deleting config map catalog-cx4rd-configmap...
Deleting catalog source catalog-cx4rd...
waiting for the catalog source catalog-cx4rd-464wc pod to be deleted...
waiting for the catalog source catalog-cx4rd-464wc pod to be deleted...
waiting for the catalog source catalog-cx4rd-464wc pod to be deleted...
waiting for the catalog source catalog-cx4rd-464wc pod to be deleted...
waiting for the catalog source catalog-cx4rd-464wc pod to be deleted...
waiting for the catalog source catalog-cx4rd-464wc pod to be deleted...
[AfterEach] Catalog represents a store of bundles which OLM can use to install Operators
  /home/perdasilva/repos/perdasilva/operator-framework-olm/staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go:47
cleaning up ephemeral test resources...
deleting test subscriptions...
deleting test installplans...
deleting test catalogsources...
deleting test crds...
deleting test csvs...
test resources deleted

• [SLOW TEST:13.239 seconds]
Catalog represents a store of bundles which OLM can use to install Operators
/home/perdasilva/repos/perdasilva/operator-framework-olm/staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go:36
  delete internal registry pod triggers recreation
  /home/perdasilva/repos/perdasilva/operator-framework-olm/staging/operator-lifecycle-manager/test/e2e/catalog_e2e_test.go:529
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 1 of 179 Specs in 13.483 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 178 Skipped
PASS
```

End-to-end: Catalog represents a store of bundles which OLM can use to install Operators image update
```
TBD
```

### Disabling Copied CSVs

End-to-end: Disabling copied CSVs when an operator is installed in AllNamespace mode [FLAKE] should have Copied CSVs in all other namespaces
End-to-end: Disabling copied CSVs when Copied CSVs are disabled [FLAKE] should be reflected in the olmConfig.Status.Condition array that the expected number of copied CSVs exist

```bash
$ make e2e WHAT=operator-lifecycle-manager E2E_INSTALL_NS=openshift-operator-lifecycle-manager E2E_TEST_NS=openshift-operators TEST="Disabling copied CSVs"

Ran 5 of 179 Specs in 55.337 seconds
SUCCESS! -- 5 Passed | 0 Failed | 0 Pending | 174 Skipped
```
### ClusterServiceVersion

End-to-end: ClusterServiceVersion when a CustomResourceDefinition was installed alongside a ClusterServiceVersion when an unassociated ClusterServiceVersion in different namespace owns the same CRD can satisfy the unassociated ClusterServiceVersion's ownership requirement

```bash
$ make e2e WHAT=operator-lifecycle-manager E2E_INSTALL_NS=openshift-operator-lifecycle-manager E2E_TEST_NS=openshift-operators TEST="ClusterServiceVersion" 

Summarizing 1 Failure:

[Fail] ClusterServiceVersion [It] multiple API services on a single pod 
/home/perdasilva/repos/perdasilva/operator-framework-olm/staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go:4711

Ran 37 of 179 Specs in 751.008 seconds
FAIL! -- 36 Passed | 1 Failed | 0 Pending | 142 Skipped

$ make e2e WHAT=operator-lifecycle-manager E2E_INSTALL_NS=openshift-operator-lifecycle-manager E2E_TEST_NS=openshift-operators TEST="multiple API services on a single pod" 

ClusterServiceVersion
/home/perdasilva/repos/perdasilva/operator-framework-olm/staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go:44
  multiple API services on a single pod
  /home/perdasilva/repos/perdasilva/operator-framework-olm/staging/operator-lifecycle-manager/test/e2e/csv_e2e_test.go:4089
------------------------------
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 1 of 179 Specs in 9.675 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 178 Skipped
```

**Comment by timflannagan** [comment]
#269 merged - closing as a duplicate.

/close

**Pull request closed without merging**
