### PR TITLE
Bug 2020484: Refactor installer to surface certificate rotation (#2775)

### PR DESCRIPTION
**Pull request by perdasilva**
Signed-off-by: perdasilva <perdasilva@redhat.com>
Upstream-repository: operator-lifecycle-manager
Upstream-commit: 9ced412f3e263b8827680dc0ad3477327cd9a508

### CODE REVIEW

**Comment by jianzhangbjz** [comment]
LGTM based on https://bugzilla.redhat.com/show_bug.cgi?id=2020484#c55
/label qe-approved

**Review by timflannagan — APPROVED** [review]

**Comment by timflannagan** [comment]
Holding so the bot doesn't go crazy.

/hold

**Pull request merged**
