### PR TITLE
[WIP] OCPBUGS-31547: UPSTREAM: <carry>: disable collect-profiles cronjob

### PR DESCRIPTION
**Pull request by perdasilva**
We've made some significant perf improvements in the last release and this job is challenging to maintain. Disabling it for now, but leaving the bits to potentially serve it if we want to manually configure the job on a customer cluster.

For the microshift manifests, deleting the manifest entirely because there is no cvo for microshift

### CODE REVIEW

**Comment by perdasilva** [comment]
This is a clone + (possible) fix of #724

**Comment by tmshort** [comment]
The tests are failing pretty early, all with the same reason.

**Pull request closed without merging**
