### PR TITLE
OLM-2726, OCPBUGS-643: downstreaming `opm serve` changes from operator-registry

### PR DESCRIPTION
**Pull request by grokspawn**
including two commits which seem to be of equal priority to pipeline:

- 215f413e do not fatally exit from serve commands (#1016)
- 494b68e6 opm serve: use pre-existing cache, if set and up-to-date (#1005)

### CODE REVIEW

**Review by timflannagan — APPROVED** [review]

**Comment by Xia-Zhao-rh** [comment]
Hi, @grokspawn 
I tested it, but failed.
catsrc is not ready due to "compute digest: compute hash: write tar: open /tmp/cache/cache: permission denied"
Please check detail information in bellow jira:
https://issues.redhat.com/browse/OCPBUGS-643
Thanks

**Review by timflannagan — APPROVED** [review]

**Pull request merged**
