### PR TITLE
OCPBUGS-31842: copy-content: delete destination dirs before copying (#3197)

### PR DESCRIPTION
**Pull request by joelanford**
Upstream-repository: operator-lifecycle-manager
Upstream-commit: 3ed3c63ea9f724da7d51062ab7f21da611dc6628

### CODE REVIEW

**Comment by perdasilva** [comment]
please also make sure `master/4.16` is good. The parent bug is [here](https://issues.redhat.com/browse/OCPBUGS-31850). The fix came through a downstream sync PR.

**Review by KeenonLee — COMMENTED** [review]
/label cherry-pick-approved

**Pull request merged**
