### PR TITLE
OCPBUGS-35305: [release-4.15] catalog-operator: delete catalog pods stuck in Terminating state due to unreachable node

### PR DESCRIPTION
**Pull request by perdasilva**
Upstream-repository: operator-lifecycle-manager
Upstream-commit: 68c24cf94371f7a73619966f9e49612fd16fa76a

### CODE REVIEW

**Comment by jianzhangbjz** [comment]
Test pass, details: https://issues.redhat.com/browse/OCPBUGS-35305
/lgtm
/label qe-approved
/label cherry-pick-approved

**Review by m1kola — APPROVED** [review]
/lgtm

**Pull request merged**
