### PR TITLE
sync: Update staging directories 04-05

### PR DESCRIPTION
**Pull request by timflannagan**
Update all of the staging directories with the changes that have landed since the initial u/d sync PR.

### CODE REVIEW

**Review by dinhxuanvu — COMMENTED** [review]
/lgtm

**Comment by timflannagan** [comment]
```
: [sig-arch] ocp payload should be based on existing source OLM version should contain the source commit id [Suite:openshift/conformance/parallel]
[It] OLM version should contain the source commit id [Suite:openshift/conformance/parallel]
  github.com/openshift/origin/test/extended/olm/olm.go:141
Apr  6 02:28:46.829: INFO: Running 'oc --kubeconfig=/tmp/kubeconfig-3379498260 get -n openshift-operator-lifecycle-manager pods -l app=catalog-operator -o=jsonpath={.items[0].metadata.name}'
STEP: get olm version from pod catalog-operator-5668fd9856-tjpzn
Apr  6 02:28:47.026: INFO: Running 'oc --kubeconfig=/tmp/kubeconfig-3379498260 exec -n openshift-operator-lifecycle-manager catalog-operator-5668fd9856-tjpzn -c catalog-operator -- olm --version'
Apr  6 02:28:48.370: INFO: olm source git commit ID:cd62315c8fa127132456fff0dcd8dac25f6907ae
Apr  6 02:28:48.370: INFO: Running 'oc --kubeconfig=/tmp/kubeconfig-3379498260 get -n openshift-operator-lifecycle-manager pods -l app=olm-operator -o=jsonpath={.items[0].metadata.name}'
STEP: get olm version from pod olm-operator-d7c55c657-mstn5
Apr  6 02:28:48.666: INFO: Running 'oc --kubeconfig=/tmp/kubeconfig-3379498260 exec -n openshift-operator-lifecycle-manager olm-operator-d7c55c657-mstn5 -c olm-operator -- olm --version'
Apr  6 02:28:49.689: INFO: olm source git commit ID:cd62315c8fa127132456fff0dcd8dac25f6907ae
Apr  6 02:28:49.689: INFO: Running 'oc --kubeconfig=/tmp/kubeconfig-3379498260 get -n openshift-operator-lifecycle-manager pods -l app=packageserver -o=jsonpath={.items[0].metadata.name}'
STEP: get olm version from pod packageserver-76fd8f74c6-6vqht
Apr  6 02:28:49.918: INFO: Running 'oc --kubeconfig=/tmp/kubeconfig-3379498260 exec -n openshift-operator-lifecycle-manager packageserver-76fd8f74c6-6vqht -c packageserver -- olm --version'
Apr  6 02:30:59.782: INFO: Error running /usr/bin/oc --kubeconfig=/tmp/kubeconfig-3379498260 exec -n openshift-operator-lifecycle-manager packageserver-76fd8f74c6-6vqht -c packageserver -- olm --version:
StdOut>
error: error sending request: Post "https://api.ci-op-ftt0msdp-b08f5.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:6443/api/v1/namespaces/openshift-operator-lifecycle-manager/pods/packageserver-76fd8f74c6-6vqht/exec?command=olm&command=--version&container=packageserver&stderr=true&stdout=true": dial tcp 35.222.78.106:6443: connect: connection timed out
StdErr>
error: error sending request: Post "https://api.ci-op-ftt0msdp-b08f5.XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX:6443/api/v1/namespaces/openshift-operator-lifecycle-manager/pods/packageserver-76fd8f74c6-6vqht/exec?command=olm&command=--version&container=packageserver&stderr=true&stdout=true": dial tcp 35.222.78.106:6443: connect: connection timed out
```

Looking at both of those [package-server replica logs](https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/origin-ci-test/pr-logs/pull/openshift_operator-framework-olm/278/pull-ci-openshift-operator-framework-olm-master-e2e-gcp/1511505366964244480/artifacts/e2e-gcp/gather-extra/artifacts/pods/openshift-operator-lifecycle-manager_packageserver-76fd8f74c6-6vqht_packageserver.log), it's unclear to me what's the root cause there.

**Pull request merged**
