### PR TITLE
Psa downstream

### PR DESCRIPTION
**Pull request by anik120**
Namespace currently look like: 
```
$ oc get ns openshift-operator-lifecycle-manager -o yaml  
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    openshift.io/node-selector: ""
    openshift.io/sa.scc.mcs: s0:c20,c0
    openshift.io/sa.scc.supplemental-groups: 1000380000/10000
    openshift.io/sa.scc.uid-range: 1000380000/10000
    workload.openshift.io/allowed: management
  creationTimestamp: "2022-08-08T20:43:32Z"
  labels:
    kubernetes.io/metadata.name: openshift-operator-lifecycle-manager
    olm.operatorgroup.uid/05abd798-6c32-444f-b464-8d6b055c1782: ""
    olm.operatorgroup.uid/0a8c1277-46e3-4fc8-a1cc-8aa53df77f87: ""
    openshift.io/cluster-monitoring: "true"
    openshift.io/scc: anyuid
  name: openshift-operator-lifecycle-manager
.
.

oc get ns openshift-operators -o yaml 
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    openshift.io/node-selector: ""
    openshift.io/sa.scc.mcs: s0:c20,c10
    openshift.io/sa.scc.supplemental-groups: 1000400000/10000
    openshift.io/sa.scc.uid-range: 1000400000/10000
    workload.openshift.io/allowed: management
  creationTimestamp: "2022-08-09T17:25:15Z"
  labels:
    kubernetes.io/metadata.name: openshift-operators
    openshift.io/scc: anyuid
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/enforce-version: v1.24
  name: openshift-operators
.
.
```
Notice the `baseline` profile enforced in `openshift-operators` namespace, to allow exsiting CSVs to install ☝🏽.
 
Workloads all working seamlessly with the right securityContext configs: 
```
$ oc get pod catalog-operator-569796f9fc-22zp2 -n openshift-operator-lifecycle-manager -o yaml | grep securityContext -A 6
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsUser: 1000380000
    terminationMessagePath: /dev/termination-log
--
  securityContext:
    fsGroup: 1000380000
    runAsNonRoot: true
    seLinuxOptions:
      level: s0:c20,c0
    seccompProfile:
      type: RuntimeDefault

$ oc get pod olm-operator-59df754788-j4qm8 -n openshift-operator-lifecycle-manager -o yaml | grep securityContext -A 6
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsUser: 1000380000
    terminationMessagePath: /dev/termination-log
--
  securityContext:
    fsGroup: 1000380000
    runAsNonRoot: true
    seLinuxOptions:
      level: s0:c20,c0
    seccompProfile:
      type: RuntimeDefault

$ oc get pod package-server-manager-69d7b66648-7kzsp -n openshift-operator-lifecycle-manager -o yaml | grep securityContext -A 6
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: FallbackToLogsOnError
--
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000380000
    seLinuxOptions:
      level: s0:c20,c0
    seccompProfile:
      type: RuntimeDefault

```

```
$ oc get pods -n openshift-marketplace 
NAME                                    READY   STATUS    RESTARTS   AGE
certified-operators-xbpbt               1/1     Running   0          23m
community-operators-vfwgb               1/1     Running   0          9m17s
marketplace-operator-5df96fcb9c-cx6pq   1/1     Running   0          29m
redhat-marketplace-zw7bd                1/1     Running   0          23m
redhat-operators-d8cbk                  1/1     Running   0          23m

$ oc get pod community-operators-vfwgb -n openshift-marketplace -o yaml | grep securityContext -A 6
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: false
      runAsNonRoot: true
--
  securityContext:
    fsGroup: 1000280000
    seLinuxOptions:
      level: s0:c17,c4
    seccompProfile:
      type: RuntimeDefault
  serviceAccount: community-operators

```

Test to make sure installing operator in the `openshift-operator` namespace works as expected: 

1) installed the aerospike-kubernetes-operator from the OperatorHub console (that installs the operator in the `openshift-operators` namespace) 
```
$ oc get sub -n openshift-operators                   
NAME                            PACKAGE                         SOURCE                CHANNEL
aerospike-kubernetes-operator   aerospike-kubernetes-operator   community-operators   alpha

$ oc get pods -n openshift-marketplace 
NAME                                                              READY   STATUS      RESTARTS   AGE
5ce4a54e377765068d69d5a13713476ef8bfa345dd551448534d5f80abxhlcr   0/1     Completed   0          3m14s
certified-operators-gmcm7                                         1/1     Running     0          41m
community-operators-dmfdf                                         1/1     Running     0          41m
marketplace-operator-6ff65457ff-2hgvl                             1/1     Running     0          47m
redhat-marketplace-zn9bw                                          1/1     Running     0          41m
redhat-operators-q6m65                                            1/1     Running     0          41m

# check that the job has the right security context configs: 
$ oc get pod 5ce4a54e377765068d69d5a13713476ef8bfa345dd551448534d5f80abxhlcr -n openshift-marketplace -o yaml | grep securityContext -A 6
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1000270000
--
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1000270000
--
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      runAsNonRoot: true
      runAsUser: 1000270000
--
  securityContext:
    fsGroup: 1000270000
    seLinuxOptions:
      level: s0:c16,c15
    seccompProfile:
      type: RuntimeDefault

$ oc get csv -n openshift-operators 
NAME                                   DISPLAY                         VERSION   REPLACES   PHASE
aerospike-kubernetes-operator.v2.1.0   Aerospike Kubernetes Operator   2.1.0                Succeeded

$ oc get pods -n openshift-operators 
NAME                                                     READY   STATUS    RESTARTS   AGE
aerospike-operator-controller-manager-587678b6fc-67j7v   2/2     Running   0          32s
aerospike-operator-controller-manager-587678b6fc-xhswq   2/2     Running   0          32s
```

### CODE REVIEW

**Review by timflannagan — APPROVED** [review]

**Comment by timflannagan** [comment]
Looks like b2b test case failures.

/hold

**Comment by anik120** [comment]
That's strange, looks like the test `[It] cleanup csvs with bad namespace annotation` is failing, and I thought I'd fixed it in [this commit](https://github.com/operator-framework/operator-lifecycle-manager/pull/2820/commits/9cde3f08de55d44332fa7afe19126ce4e4b9c25f). I did remove the `flaky` annotation from the test, and it passes in upstream, but looks like it's failing in a [different stage](https://github.com/openshift/operator-framework-olm/pull/349/commits/b357850966b44575055924b4d3317d797c07c079#diff-685ef13e87c308bd27e50993b4fa0394d5fa15b35dce93bb997fb7015afae3cbR2035) than [where the actual fix is](https://github.com/openshift/operator-framework-olm/pull/349/commits/b357850966b44575055924b4d3317d797c07c079#diff-685ef13e87c308bd27e50993b4fa0394d5fa15b35dce93bb997fb7015afae3cbR2046). Regardless, the commit did introduce that change, but looks like it was [expected before too](https://github.com/operator-framework/operator-lifecycle-manager/pull/2820/commits/9cde3f08de55d44332fa7afe19126ce4e4b9c25f#diff-cf741e0936629b706c116daf7050bc3dc92f37a3cd7cad348f6d84a448acf5f1L2025) that this is a flaky area, 
/test e2e-gcp-olm
to see if it fails in the same spot again so that I can investigate it further tomorrow. Maybe it's just a case of introducing the `flaky` annotation back into the test, since I just ran the test upstream it passes every time, looks like the test passes in aws, it's strange that there could be a delta in gcp for this test.

**Comment by anik120** [comment]
Found the problem, fix posted in https://github.com/operator-framework/operator-lifecycle-manager/pull/2837, once that merges will pull that commit in this PR

**Comment by anik120** [comment]
>Pod pending timeout.
smh. /retest

**Comment by anik120** [comment]
c'mon man 
/retest

**Comment by anik120** [comment]
@timflannagan would you do the honors please 🥲

**Review by timflannagan — APPROVED** [review]

**Pull request merged**
