### PR TITLE
Bug 2094303: fix(vendor/scoped): bump k8s version to 1.24, go version to 1.18 and fix scoped client (#2794)

### PR DESCRIPTION
**Pull request by dinhxuanvu**
* fix(vendor): bump k8s version to 1.24 and go version to 1.18

Signed-off-by: Vu Dinh <vudinh@outlook.com>

* Update clock package from apimachinery to utils

The apimachinery/pkg/util/clock is deprecated and all clock utils is
on k8s.io/utils/clock repo instead.

Signed-off-by: Vu Dinh <vudinh@outlook.com>

* fix(go.mod): pin opentelemetry packages into specific versions

Signed-off-by: Vu Dinh <vudinh@outlook.com>
Co-authored-by: timflannagan <timflannagan@gmail.com>

* fix(scoped): update scoped client library to handle token secret

In k8s 1.24, token secret is no longer referenced in ServiceAccount.
By listing all secrets in the namespace and then filter them with
SA name via kubernetes.io/service-account.name annotation, the
token secret can be retrieved successfully.

Signed-off-by: Vu Dinh <vudinh@outlook.com>

* fix(e2e): Fix several RBAC-related e2e test cases

Create token secret for ServiceAccount to ensure those SA
is valid for scoped client use.

Signed-off-by: Vu Dinh <vudinh@outlook.com>

Upstream-repository: operator-lifecycle-manager
Upstream-commit: fd9017345aa0fbd7aaed7f0937ff23fca33a9df0

Co-authored-by: timflannagan <timflannagan@gmail.com>

### CODE REVIEW

**Comment by perdasilva** [comment]
We'll need someone else to lgtm

**Review by timflannagan — APPROVED** [review]

**Comment by timflannagan** [comment]
It looks like we might need to bump the Go version in the root module.

**Pull request merged**
