### PR TITLE
Bug 1934080: Preserve existing ServiceAccount owner references during installs.

### PR DESCRIPTION
**Pull request by timflannagan**
A ServiceAccount requirement in a ClusterServiceVersion is considered
unsatisfied if it is not owned by the CSV _and_ it is owned by a
different CSV. During InstallPlan execution, owner references in
ServiceAccount steps replace existing owner references. As a result, a
CSV that is being replaced may transition to Failed (requirements not
met) and block replacement.

Signed-off-by: Ben Luddy <bluddy@redhat.com>

Upstream commit: 1e463a9076f57d77122ab6ef22d445189776c3aa

### CODE REVIEW

**Comment by timflannagan** [comment]
My bad - forgot to update the root vendor. Should be fine now passing that verify check.

**Comment by timflannagan** [comment]
Not sure how I missed that these changes aren't in the right staging tree.

/hold

**Comment by timflannagan** [comment]
/retest

```

failed to acquire lease: resources not found
--
```

**Comment by timflannagan** [comment]
Couldn't acquire a lease

/retest

**Comment by ecordell** [comment]
/hold cancel

a major cause of e2e-upgrade failures just merged

**Comment by timflannagan** [comment]
```
failed to acquire lease: status 503 Service Unavailable, status code 503
--
```

/retest

**Pull request merged**
