### PR TITLE
[release-4.8] Bug 2074680: Emit CSV metric on startup

### PR DESCRIPTION
**Pull request by anik120**
4.8 backport of https://github.com/openshift/operator-framework-olm/pull/239

### CODE REVIEW

**Comment by perdasilva** [comment]
@anik120 sorry dude - I was just cycling some failed jobs - thought I'd be helpful. Hopefully, I didn't screw anything up...

**Review by timflannagan — APPROVED** [review]

**Comment by anik120** [comment]
/hold cancel
Turns out this was failing because [this commit](https://github.com/openshift/operator-framework-olm/pull/129/commits/ec51a3dd27f2f284c535fc436bc00825812b817d) from `master` that has e2e changes was not backported along with the csv metric commits. Updated the PR to include the commit.

**Comment by anik120** [comment]
Nice @timflannagan @perdasilva this PR's finally green 🎉  just needs an lgtm

**Comment by bandrade** [comment]
```
oc version  
Client Version: 4.8.0-0.nightly-2021-05-03-072623
Server Version: 4.8.0-0.ci.test-2022-04-29-142539-ci-ln-mdrtg5k-latest
Kubernetes Version: v1.21.8-1466+ed4d8fd9e83b31-dirty


oc exec catalog-operator-6957f5496b-4lbb8  -n openshift-operator-lifecycle-manager -- olm --version
OLM version: 0.17.0
git commit: d2ddc316ced0342a680655fde4415b08d29a3891

1, install some operators
oc get csv -A | grep -v elasticsearch | grep -v nginx-ingress | grep -v must-gather
NAMESPACE                              NAME                        DISPLAY                     VERSION    REPLACES   PHASE
openshift-logging                      cluster-logging.5.3.6-46    Red Hat OpenShift Logging   5.3.6-46              Succeeded
openshift-operator-lifecycle-manager   packageserver               Package Server              0.17.0                Succeeded
test-1                                 anzo-operator               Anzo Operator               2.0.1                 Succeeded
test-3                                 cockroach-operator.v2.6.0   CockroachDB Operator        2.6.0                 Succeeded

2, port-fowarding to the olm-operator pod and curling the metrics endpoint
oc port-forward olm-operator-8c8c5458-8776c 8081 -n openshift-operator-lifecycle-manager                      1 ↵
Forwarding from 127.0.0.1:8081 -> 8081
Forwarding from [::1]:8081 -> 8081
Handling connection for 8081
Handling connection for 8081

curl -k https://localhost:8081/metrics | grep csv                                                             1 ↵
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6890    0  6890    0     0  11445     # HELP csv_count Number of CSVs successfully registered
 0# TYPE csv_count gauge
 -csv_count 4
-:-# HELP csv_succeeded Successful CSV install
-:# TYPE csv_succeeded gauge
-- csv_succeeded{name="anzo-operator",namespace="test-1",version="2.0.1"} 1
--csv_succeeded{name="cluster-logging.5.3.6-46",namespace="openshift-logging",version="5.3.6-46"} 1
:-csv_succeeded{name="cockroach-operator.v2.6.0",namespace="test-3",version="2.6.0"} 1
-csv_succeeded{name="packageserver",namespace="openshift-operator-lifecycle-manager",version="0.17.0"} 1
:# HELP csv_upgrade_count Monotonic count of CSV upgrades
--# TYPE csv_upgrade_count counter
 -csv_upgrade_count 0


oc delete pod olm-operator-8c8c5458-8776c -n openshift-operator-lifecycle-manager       
pod "olm-operator-8c8c5458-8776c" deleted

oc port-forward olm-operator-8c8c5458-z5n2f 8081 -n openshift-operator-lifecycle-manager                    130 ↵
Forwarding from 127.0.0.1:8081 -> 8081
Forwarding from [::1]:8081 -> 8081
Handling connection for 8081

url -k https://localhost:8081/metrics | grep csv
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0# HELP csv_count Number of CSVs successfully registered
# TYPE csv_count gauge
csv_count 4
# HELP csv_succeeded Successful CSV install
# TYPE csv_succeeded gauge
csv_succeeded{name="anzo-operator",namespace="test-1",version="2.0.1"} 1
csv_succeeded{name="cluster-logging.5.3.6-46",namespace="openshift-logging",version="5.3.6-46"} 1
csv_succeeded{name="cockroach-operator.v2.6.0",namespace="test-3",version="2.6.0"} 1
csv_succeeded{name="packageserver",namespace="openshift-operator-lifecycle-manager",version="0.17.0"} 1
# HELP csv_upgrade_count Monotonic count of CSV upgrades
# TYPE csv_upgrade_count counter
csv_upgrade_count 0
100  6893    0  6893    0     0   9391      0 --:--:-- --:--:-- --:--:--  9391


```

/lgtm

**Pull request merged**
