### PR TITLE
[release-4.8] Bug 1994038: clarify maxOpenShiftVersion upgrade error message

### PR DESCRIPTION
**Pull request by timflannagan**
Signed-off-by: Ankita Thomas <ankithom@redhat.com>

Upstream-repository: operator-lifecycle-manager
Upstream-commit: 7c2f004129b037333c4fe29ec5ac94b5e1247564

### CODE REVIEW

**Comment by timflannagan** [comment]
Manual cherrypick of #169 as pulling down the api repository commits produced a merge conflict as relevant changes made to the community packages were introduced after the 4.8 release. Dropping those commits entirely and just cherrypicking the updated message.

**Comment by sdodson** [comment]
Infra flakes on yum repos?
/retest-required

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Comment by sdodson** [comment]
Setting `cherry-pick-approved` to get this in as a late fix.

**Comment by sdodson** [comment]
/override ci/prow/e2e-upgrade
This does not affect node availability.

**Pull request merged**
