### PR TITLE
chore: remove upstream OWNERS/MAINTAINERS files

### PR DESCRIPTION
**Pull request by anik120**
This PR removes the OWNERS and MAINTAINERS files that are used
in the upstream repo, but aren't relevant in this repo.

Signed-off-by: Anik Bhattacharjee <anikbhattacharya93@gmail.com>

### CODE REVIEW

**Comment by anik120** [comment]
/hold 

`only staging commits (i.e. from an upstream cherry-pick) may change staging`

oops. 

Will come back to this later.

**Comment by perdasilva** [comment]
@anik120 can we clean up this PR and get it through?

**Comment by perdasilva** [comment]
closing due to lack of activity

**Pull request closed without merging**
