### PR TITLE
OCPBUGS-1326: Opm serve cmds

### PR DESCRIPTION
**Pull request by grokspawn**
Earlier PR missed two lines to expose the caching commands.

### CODE REVIEW

**Review by timflannagan — APPROVED** [review]

**Review by awgreene — APPROVED** [review]
Looks good!

**Review by dinhxuanvu — COMMENTED** [review]
/lgtm

**Comment by awgreene** [comment]
/label backport-risk-assessed

This change is required to introduce the caching flags that enable the caching features already backported.

**Pull request merged**
