### PR TITLE
OPRUN-2913: Sync api, operator-registry, operator-lifecycle-manager downstream

### PR DESCRIPTION
**Pull request by tmshort**
This is a *big* merge of the upstream repositories into the downstream mono-repo.

Due to different levels of activity in each repository, they were at different level of the k8s API, and this had to be resolved upstream before downstreaming. This involved updated quite a number of components in `go.mod`/`go.sum`.

In order to do this sync as cleanly as possible, _because various bug fixes were downstreamed independently_, I updated the sync scripts in the `scripts` directory. The first change was to interleave (based on the commit timestamp) the syncing of individual commits from the source repositories, in the future hope that it will make large merges like this easier. Doing each source repo one-at-a-time can cause `go.mod` components to be upgraded by one repo, and then regressed by another repo, before being upgraded again. Interleaving the commits from the repositories based on date helps alleviate this scenario.

The second change was to note if there were any changes to the `go.mod` files, and if so, give the merger (e.g. me in this case) the opportunity (by pausing) to evaluate if there were any regressions in the `go.mod` file. Then the merger can open a shell in another window to evaluate the `go.mod` file to see if it needs to be modified and/or reverted.

The third change was to handle failures of `make manifests` in a similar way. If `make manifests` fails, the update scripts will pause to allow the merge to evaluate the results. This was especially useful as `make manifests` was failing due to the inconsistent versioning of the k8s API in each of the source repositories.

In this merge, the k8s APIs are now at v0.27.2.

### CODE REVIEW

**Comment by tmshort** [comment]
It appears `ci/prow/e2e-gcp-ovn`/`ci/prow/e2e-gcp-olm` are failing because `oc get packagemanifest` (singular) is failing to retrieve any resources.
Creating a cluster with this PR, `oc get packagemanifests` (plural) works, but `oc get packagemanifest` (singular) fails. I will need to test a cluster w/o this PR to see which one works.
One of the upstream commits required the addition of `GetSingularName()` for `packagemanifests`, which you think would not be a problem (and would certainly not cause _this_ problem).

**Comment by tmshort** [comment]
Vanilla 4.14:
```
tshort@cube:~/OPRUN-2913$ oc get packagemanifest | wc
    432    1847   33264
tshort@cube:~/OPRUN-2913$ oc get packagemanifests | wc
    432    1847   33264
tshort@cube:~/OPRUN-2913$

**Comment by tmshort** [comment]
It's a change in the upstream behavior; verified on a vanilla 4.14 cluster, and on https://github.com/operator-framework/operator-lifecycle-manager/commit/11b66efd9daaac736ac011f16f0c0686d54e0a79 (tip of master) vs https://github.com/operator-framework/operator-lifecycle-manager/commit/4564b26d9a35cda72a5e6833cbf7a84175512106 (before k8s updates)

**Review by ankitathomas — APPROVED** [review]
/lgtm

**Comment by tmshort** [comment]
The CI complains about the `OWNERS` files are all about those in the `staging` directories. Do we care? Should I remove those individuals, or even the `OWNERS` files themselves?

**Comment by 87utierrez** [comment]
@tmshort Hi, my name is Hector, I was hoping that you could help and share with me as I'm new with go and development.  with run a build to create an image from this repo. 

I've cloned this repo and made some changes to the go. mod and run the following command 

- go mod tidy
- go mod verify
- go mod vendor
- go  test ./... 
-
It came back with the program, not an importable package.  

- what I'm trying to accomplish is to use this registry  - within my  docker file
 FROM registry.redhat.io/openshift4/ose-operator-registry:v4.13.0-202306072029.p0.gce46f5b.assembly.stream
I'm pulling the /bin/opm and /bin/grpc_health_probe into my image. The reason why I made changes to the go mod list is to update the packages that have fixes from the previous version. 

The ask is after making those changes and updating the go.sum , how do I rebuild the manifest to have an image made?
I could really use your help --- desperate.

**Comment by tmshort** [comment]
>@tmshort Hi, my name is Hector, I was hoping that you could help and share with me as I'm new with go and development. with run a build to create an image from this repo.

Hi @87utierrez, this is not an appropriate forum for this type of discussion. I suggest joining the **#olm-dev** channel in the  Kubernetes Slack instance: https://kubernetes.slack.com/archives/C0181L6JYQ2

**Review by ankitathomas — APPROVED** [review]
/lgtm

**Comment by 87utierrez** [comment]
I don’t have an account on there ? Hector Gutierrez On Jul 24, 2023, at 9:23 AM, Todd Short ***@***.***> wrote:﻿

@tmshort Hi, my name is Hector, I was hoping that you could help and share with me as I'm new with go and development. with run a build to create an image from this repo.

Hi @87utierrez, this is not an appropriate forum for this type of discussion. I suggest joining the #olm-dev channel in the  Kubernetes Slack instance: https://kubernetes.slack.com/archives/C0181L6JYQ2

**Comment by m1kola** [comment]
@87utierrez you can create a slack account and joint the community using this link - https://slack.k8s.io/

**Pull request merged**
