### PR TITLE
Skuznets/bump vendor

### PR DESCRIPTION
**Pull request by stevekuznetsov**

### CODE REVIEW

**Comment by tmshort** [comment]
https://github.com/openshift/operator-framework-olm/pull/585 pulls in from api, operator-registry and olm...

**Comment by tmshort** [comment]
Yeah, I pulled down your PR, and it wants to make changes to `staging/operator-registry/go.sum` because of other changes to upstream with the CVE we're dealing with. Might want to incorporate #585.

**Comment by stevekuznetsov** [comment]
Had a bug in the bumper, fixed in #593 

Won't re-base since the other PR has not merged yet

**Comment by dinhxuanvu** [comment]
I recommend pulling in this [commit ](https://github.com/operator-framework/operator-lifecycle-manager/pull/3070) which should improve some of the failed test cases in this PR.

**Comment by stevekuznetsov** [comment]
```
$ grep 'labeller complete' ./pods/olm-operator-6f9c4c89c4-n9qxf/olm-operator/olm-operator/logs/current.log  | grep -Po '(?<=gvr=").+' | sort | uniq -c
   2051 apps/v1, Resource=deployments" index=0
   6759 rbac.authorization.k8s.io/v1, Resource=clusterrolebindings" index=0
   6755 rbac.authorization.k8s.io/v1, Resource=clusterrolebindings" index=1
  66749 rbac.authorization.k8s.io/v1, Resource=clusterroles" index=1

$ grep 'labeller complete' ./pods/catalog-operator-7fdcd4c7df-pgp2p/catalog-operator/catalog-operator/logs/previous.log | grep -Po '(?<=gvr=").+' | sort | uniq -c
      2 apiextensions.k8s.io/v1, Resource=customresourcedefinitions" index=0
      5 batch/v1, Resource=jobs" index=0
      6 rbac.authorization.k8s.io/v1, Resource=rolebindings" index=0
      6 rbac.authorization.k8s.io/v1, Resource=rolebindings" index=1
     29 rbac.authorization.k8s.io/v1, Resource=roles" index=0
      6 rbac.authorization.k8s.io/v1, Resource=roles" index=1
      4 /v1, Resource=pods" index=0
      4 /v1, Resource=serviceaccounts" index=0
      4 /v1, Resource=services" index=0
```

For some reason, we are not seeing the first labeller for `ClusterRoles` in the `olm-operator` ever succeed. That's the one that adds `olm.managed=true` to those `ClusterRoles.

**Comment by stevekuznetsov** [comment]
I also looked at one of the ClusterRoles in question and in the audit logs the only requests referring to that object were apply calls from the labellers. Apply will merge the labels together, so having two clients using server-side apply to ensure the presence of two disjoint sets of labels should be totally fine - they should not override each other. I'm going to have to look at the cluster during the upgrade to debug more. What a mess.

**Comment by tmshort** [comment]
> For some reason, we are not seeing the first labeller for ClusterRoles in the olm-operator ever succeed. 

Do you know what the error is? Where is this code?

**Comment by stevekuznetsov** [comment]
@tmshort there is no error in the logs whatsoever. We see successful labelling, but never finishes (and it re-labels the same object many times). The code is in `labeller/labels.go`. It's the same generic code that labels all the other objects - the only difference is that for `ClusterRoles`, both that and `labels/rbac.go` are running. Although, for `ClusterRoleBindings`, `Roles` and `RoleBindings`, that should also be the case. It may be that there are no objects of those types, though.

**Review by dinhxuanvu — COMMENTED** [review]
/lgtm

**Comment by stevekuznetsov** [comment]
```
{  fail [github.com/openshift/origin/test/e2e/upgrade/upgrade.go:186]: during upgrade to registry.build03.ci.openshift.org/ci-op-rsk7x79h/release@sha256:1e87362d2b47f6193340b37ae97bc9b859f8c941c23fd681477270bd7107303e: Cluster did not complete upgrade: timed out waiting for the condition: Could not update prometheusrule "openshift-operator-lifecycle-manager/olm-alert-rules" (842 of 862): the object is invalid, possibly due to local cluster configuration
Ginkgo exit error 1: exit with code 1}
```

/retest

Did we mess up alerting rules somehow ... ?

**Comment by stevekuznetsov** [comment]
```
{  fail [github.com/openshift/origin/test/e2e/upgrade/upgrade.go:186]: during upgrade to registry.build03.ci.openshift.org/ci-op-rsk7x79h/release@sha256:26f463d7c52cc21df568b229de86541c3fa0fafacf05e5de68cc07d47b9096b0: Cluster did not complete upgrade: timed out waiting for the condition: Could not update prometheusrule "openshift-operator-lifecycle-manager/olm-alert-rules" (842 of 862): the object is invalid, possibly due to local cluster configuration
```

OK - yeah ... bona fide break. How!?!?

**Pull request merged**
