### PR TITLE
OPRUN-3063: Microshift manifests: Ignore "*.removed.yaml" files in kustomization.yaml

### PR DESCRIPTION
**Pull request by jmprusi**
As microshift doesn't have CVO, we don't need the `*.removed.yaml` files to be applied on microshift, this PR removes them from the kustomization.yaml file.

### CODE REVIEW

**Review by awgreene — APPROVED** [review]
Looks good!

**Review by awgreene — APPROVED** [review]
/lgtm

**Review by m1kola — APPROVED** [review]
/lgtm

**Pull request merged**
