### PR TITLE
Bug 1996139: chore(verify-commits): initialize variable

### PR DESCRIPTION
**Pull request by njhale**
Set a default value for a variable causing undefined errors at runtime.

This was causing the `verify` make target to fail erroneously.

### CODE REVIEW

**Review by ankitathomas — APPROVED** [review]
/lgtm

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Review by ankitathomas — CHANGES_REQUESTED** [review]
` outside_staging="$(git show --name-only "${downstream_commit}" -- ":!${staging_dir}" ':!vendor :!manifests')"`

Looks like the vendor/manifests directories need to be quoted individually, or they fail

` outside_staging="$(git show --name-only "${downstream_commit}" -- ":!${staging_dir}" ':!vendor' ':!manifests')"`

**Review by ankitathomas — APPROVED** [review]
/lgtm

**Pull request merged**
