### PR TITLE
Bump go and k8s

### PR DESCRIPTION
**Pull request by awgreene**

### CODE REVIEW

**Comment by awgreene** [comment]
This is ready to merge.
/unhold

Test is failing as expected given that one of the downstream commits had to modify a staged go dependency. 
/override verify

**Comment by awgreene** [comment]
This PR shouldn't require approval from px or docs, it may require approval from qe, but I'll leave that to @jianzhangbjz to decide.
/label px-approved
/label docs-approved

**Comment by jianzhangbjz** [comment]
LGTM, create a cluster with this PR via the cluster-bot.
```bash
MacBook-Pro:~ jianzhang$ oc get csv -n default
NAME                     DISPLAY                                    VERSION   REPLACES                 PHASE
etcdoperator.v0.9.4      etcd                                       0.9.4     etcdoperator.v0.9.2      Succeeded
rhacs-operator.v3.72.1   Advanced Cluster Security for Kubernetes   3.72.1    rhacs-operator.v3.72.0   Succeeded
MacBook-Pro:~ jianzhang$ oc get clusterversion
NAME      VERSION                                                   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.12.0-0.ci.test-2022-11-29-015710-ci-ln-icmg8qb-latest   True        False         50m     Cluster version is 4.12.0-0.ci.test-2022-11-29-015710-ci-ln-icmg8qb-latest
```
/label qe-approved

**Pull request merged**
