### PR TITLE
WIP: AUTH-481: add PSa labels to openshift namespaces

### PR DESCRIPTION
**Pull request by liouk**
- openshift-operator-lifecycle-manager
- openshift-operators

### CODE REVIEW

**Comment by liouk** [comment]
/hold
blocked by https://issues.redhat.com/browse/AUTH-482

**Comment by perdasilva** [comment]
Hi @liouk ^^ could you please run `make manifests`, then commit any changes, then run `make verify` just to double check?

**Comment by liouk** [comment]
Hi @perdasilva, thanks for pointing this out. I've committed the results of `make manifests` as a separate commit (90cb98fcca562ba3583c07bcb74a020d85e252fa). Also, `make verify` locally succeeds with the above changes.

**Comment by liouk** [comment]
Hi @perdasilva, thanks for pointing this out.

I've set the required values in `values.yaml`, however then running `make manifests` removes the labels from `manifests/0000_50_olm_00-namespace.yaml`, even if their values are defined in `values.yaml`. How can I correctly generate the labels in `manifests/0000_50_olm_00-namespace.yaml`?

**Pull request closed without merging**
