### PR TITLE
[release-4.18] OCPBUGS-46474:catalog-operator: Delete Pods that were evicted (#3459)

### PR DESCRIPTION
**Pull request by anik120**
This change adds another reason why a Pod could be detected as "dead", namely when it was evicted by the kubelet. This can happen when there is resource pressure on the Node. Then the reason will be "TerminationByKubelet".

This addresses the issue described in
https://issues.redhat.com/browse/OCPBUGS-45490

Upstream-repository: operator-lifecycle-manager
Upstream-commit: 8e39847016ba04a4d12599a8d101f4af77c389b5

### CODE REVIEW

**Review by tmshort — APPROVED** [review]
/lgtm

**Comment by LalatenduMohanty** [comment]
Can you point me to the 4.19 PR (main branch PR)? May be it automatically got synced from upstream.

**Comment by anik120** [comment]
@LalatenduMohanty it did: https://github.com/openshift/operator-framework-olm/pull/907
Here's the JIRA for it: https://issues.redhat.com/browse/OCPBUGS-45490

**Review by LalatenduMohanty — APPROVED** [review]
/lgtm

**Pull request merged**
