### PR TITLE
OCPBUGS-5523: Catalog, fatal error: concurrent map read and map write

### PR DESCRIPTION
**Pull request by dtfranz**
Problem:
The metrics pkg uses a shared map var to keep a record of Prometheus counters from Subscription objects, which is not protected from concurrent read/write access. This can result in container restarts. 

Solution: 
This PR adds a mutex to lock and unlock before and after each map access instance. Any number of requests to **read** from the map may happen concurrently, but when a **write** operation occurs nothing else can access the map until the **write** is finished.

Motivation for the change:

OCPBUGS-5523

### CODE REVIEW

**Comment by awgreene** [comment]
@dtfranz seems like a gcp failure:
```
{  failed to acquire lease for "gcp-quota-slice": resources not found}
```

**Review by tmshort — APPROVED** [review]
/lgtm

**Pull request merged**
