### PR TITLE
Bug 2095329: [release-4.10] Bump go to v1.17 (#922)

### PR DESCRIPTION
**Pull request by perdasilva**
This commit updates the operator-registry's go version
to v1.17.

Signed-off-by: Alexander Greene <greene.al1991@gmail.com>
Upstream-repository: operator-registry
Upstream-commit: c970d617ce2d77c096102e2d881a15ef680bacf9

### CODE REVIEW

**Comment by timflannagan** [comment]
It looks like we don't have a 4.11 parent BZ, so we'll need to retarget the referenced BZ to 4.11 and verify that first before we can start the backport process to the release-4.10 branch.

/hold

**Comment by perdasilva** [comment]
> It looks like we don't have a 4.11 parent BZ, so we'll need to retarget the referenced BZ to 4.11 and verify that first before we can start the backport process to the release-4.10 branch.
> 
> /hold

Does that make sense though? 4.11 is already on go1.17

**Pull request merged**
