### PR TITLE
Upstream sync

### PR DESCRIPTION
**Pull request by ankitathomas**

### CODE REVIEW

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Comment by ankitathomas** [comment]
Closing this in favor of https://github.com/openshift/operator-framework-olm/pull/187, 

https://github.com/operator-framework/operator-lifecycle-manager/pull/2216 will need to be pulled in separately

**Pull request closed without merging**
