### PR TITLE
[release-4.11] OCPBUGS-16075: fix dynamic conversion webhook

### PR DESCRIPTION
**Pull request by perdasilva**
Copy of #508: 
> This is an automated cherry-pick of #503

#508 was blocked by CI because of the global catalog changes we put in had a problem downstream. How they got in, I don't know.

### CODE REVIEW

**Comment by kuiwang02** [comment]
/hold

because I am doing pre-verifying. after that, I will cancel hold.

**Comment by kuiwang02** [comment]
pre-verify pass.

/hold cancel

**Review by m1kola — APPROVED** [review]
/lgtm

**Pull request merged**
