### PR TITLE
Bug 1953977: Add tolerant delegating auth config for PackageServer

### PR DESCRIPTION
**Pull request by timflannagan**
Make delegating auth config more tolerant to k8s API issues by adding
start up polling and exceptions for health readiness endpoints.

Signed-off-by: Nick Hale <njohnhale@gmail.com>

Upstream-commit: 59f218769d590823f516f351417cff772ba37677
Upstream-repository: operator-lifecycle-manager

### CODE REVIEW

**Review by ankitathomas — APPROVED** [review]
/lgtm

**Comment by timflannagan** [comment]
I saw https://bugzilla.redhat.com/show_bug.cgi?id=1959158 in the logs, and a `APIService install failed ...` message as well that we may need to keep an eye on in subsequent runs.

```
May 12 19:14:14.960 E clusteroperator/operator-lifecycle-manager-packageserver condition/Available status/False reason/ClusterServiceVersionNotSucceeded changed: ClusterServiceVersion openshift-operator-lifecycle-manager/packageserver is in phase Failed with reason: APIServiceInstallFailed, message: APIService install failed: forbidden: User "system:anonymous" cannot get path "/apis/packages.operators.coreos.com/v1"
May 12 19:14:14.960 - 49ms  E clusteroperator/operator-lifecycle-manager-packageserver condition/Available status/False reason/ClusterServiceVersion openshift-operator-lifecycle-manager/packageserver is in phase Failed with reason: APIServiceInstallFailed, message: APIService install failed: forbidden: User "system:anonymous" cannot get path "/apis/packages.operators.coreos.com/v1"
```

**Comment by timflannagan** [comment]
Same failure as above.

/retest

**Pull request merged**
