### PR TITLE
*: sync upstream

### PR DESCRIPTION
**Pull request by stevekuznetsov**

### CODE REVIEW

**Comment by tmshort** [comment]
> Can we wait until [operator-framework/operator-lifecycle-manager#3011](https://github.com/operator-framework/operator-lifecycle-manager/pull/3011) lands? It's also a `go-restful` update. Get all three in at the same time.

And... it's merged...

**Comment by stevekuznetsov** [comment]
Updated :)

**Comment by stevekuznetsov** [comment]
/retest

... never the same failure twice, huh

**Comment by tmshort** [comment]
Not sure why the .gitignore commit is in here?

**Comment by stevekuznetsov** [comment]
@tmshort I had the built binary on my system when creating this branch and didn't want to commit it. Should be harmless ... ?

**Comment by stevekuznetsov** [comment]
Superseded by #562

**Pull request closed without merging**
