### PR TITLE
[release-4.15] OCPBUGS-25798: Fix snapshot failure, backport e2es

### PR DESCRIPTION
**Pull request by kevinrizza**
This pr fixes an issue with deprecation propogation with certain operatorgroup contexts

Additionally, this pr pulls in a set of e2e improvements to increase our signal for release backports

### CODE REVIEW

**Comment by kevinrizza** [comment]
these test failures seem unrelated to the pull request


/test e2e-gcp-ovn

**Comment by dtfranz** [comment]
@Xia-Zhao-rh , this PR contains both #666 and e2e fixes required to enable us to merge changes to 4.15. Would you also mind giving your labels here?

**Pull request merged**
