### PR TITLE
Downstream sync

### PR DESCRIPTION
**Pull request by tmshort**

### CODE REVIEW

**Comment by dtfranz** [comment]
I'll run this once more but looks like we may have some investigating to do
/test e2e-upgrade

**Comment by tmshort** [comment]
> I'll run this once more but looks like we may have some investigating to do

This is basically @stevekuznetsov's #581, and I think e2e-upgrade may be broken in by these PRs.

**Comment by tmshort** [comment]
Closing due to #581 merging.

**Pull request closed without merging**
