### PR TITLE
OLM blocks minor OpenShift upgrades when incompatible optional operators are installed

### PR DESCRIPTION
**Pull request by njhale**
Downstreams
- https://github.com/operator-framework/operator-lifecycle-manager/pull/2081
- https://github.com/operator-framework/operator-lifecycle-manager/pull/2103
- https://github.com/operator-framework/operator-lifecycle-manager/pull/2105

Implements: [OLM-2074](https://issues.redhat.com/browse/OLM-2074) - OLM blocks minor OpenShift upgrades when incompatible optional operators are installed

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
/hold
Additional fix in https://github.com/operator-framework/operator-lifecycle-manager/pull/2105

**Comment by njhale** [comment]
/hold

Getting some consensus on whether this should merge before or after 4.8.0 is released.

**Comment by njhale** [comment]
Will be included in the upstream sync.

**Pull request closed without merging**
