### PR TITLE
test/e2e: Preserve the existing environment when using exec.Command

### PR DESCRIPTION
**Pull request by timflannagan**
Signed-off-by: timflannagan <timflannagan@gmail.com>

Upstream-commit: 91e5d90b3ea330c681656af7d0dc160ecb535876
Upstream-repository: operator-lifecycle-manager

### CODE REVIEW

**Comment by timflannagan** [comment]
This is a no-op and only affects our testing suite. Adding the required labels.

/label px-approved
/label qe-approved
/label docs-approved

**Comment by timflannagan** [comment]
lmao

**Comment by exdx** [comment]
My condolences 😄

**Comment by grokspawn** [comment]
/lgtm

waiting on tenterhooks to see e2e-gcp-olm results ...

**Comment by timflannagan** [comment]
Looks like that worked.

/override ci/prow/e2e-gcp-olm

**Pull request merged**
