### PR TITLE
Upstream OLM + API sync 12-14

### PR DESCRIPTION
**Pull request by timflannagan**

### CODE REVIEW

**Comment by timflannagan** [comment]
It looks like we didn't pull in the OLM commits in the right order last time so there were some missing test/e2e commit(s) that newer commits reference which failed the e2e-aws-olm check. Updated to include all (:crossed_fingers:) of those missing commits.

**Comment by timflannagan** [comment]
```
INFO[2021-12-16T02:39:44Z] Acquired 1 lease(s) for aws-quota-slice: [us-west-2--aws-quota-slice-03] 
INFO[2021-12-16T02:39:44Z] Running multi-stage test e2e-aws-olm         
INFO[2021-12-16T02:39:44Z] Running step e2e-aws-olm-ipi-conf.           
INFO[2021-12-16T02:39:54Z] Step e2e-aws-olm-ipi-conf succeeded after 10s. 
INFO[2021-12-16T02:39:54Z] Running step e2e-aws-olm-ipi-conf-aws.       
INFO[2021-12-16T02:40:05Z] Logs for container test in pod e2e-aws-olm-ipi-conf-aws: 
INFO[2021-12-16T02:40:05Z]   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   651  100   651    0     0   2827      0 --:--:-- --:--:-- --:--:--  2842

  0     0    0   367    0     0    838      0 --:--:-- --:--:-- --:--:--   838
/tmp/yq: line 1: syntax error near unexpected token `newline'
/tmp/yq: line 1: `<?xml version="1.0" encoding="UTF-8"?>'
```

Welp hopefully that's a transient error 

/retest

**Comment by timflannagan** [comment]
We may need to pivot to non-AWS tomorrow if infra flakes continue.

/retest-required

**Comment by anik120** [comment]
looks like it's still failing to bring up an aws cluster

/retest

**Comment by anik120** [comment]
Looks like the OLMConfig controller isn't playing well with downstream as of now. #232 just passed all test that's a clone of this PR minus the OLMConfig commit. lgtm-ing that PR so that the rest of the commits can go in, and then we can dig into the OLMConfig commit.

**Pull request closed without merging**
