### PR TITLE
provide the capability to filter mermaid output to a single package name / skipRange support (#1023)

### PR DESCRIPTION
**Pull request by grokspawn**
…

handle invalid SkipRange with output to stderr and ignoring the instance instead of dying determine package of min filter to weed out mismatches 
Upstream-repository: operator-registry
Upstream-commit: 0e53cafe2df4222611796ca252b23abac3b442aa

Signed-off-by: Jordan Keister <jordan@nimblewidget.com>

### CODE REVIEW

**Comment by perdasilva** [comment]
@grokspawn is this something that required QE? Could we update the PR title with the jira ticket?

**Comment by grokspawn** [comment]
Completely lost track of this during the transition.  Sorry, Per.  😦 
This is an enhancement of a alpha-level function.  No PX/QE/docs should be necessary.  
Normally I would try to have a tracking jira, but in light of the gap this time I'm going to see about satisfying 4.next with labels. 

/label px-approved
/label qe-approved
/label docs-approved

**Pull request merged**
