### PR TITLE
OCPBUGS-32311: [release-4.15]: Update if AlreadyExists

### PR DESCRIPTION
**Pull request by kevinrizza**
Upstream-repository: operator-lifecycle-manager
Upstream-commit: a7b6658a0eaf161433fbda9bb4fa66adb0862aaa

Upstream-repository: operator-lifecycle-manager
Upstream-commit: 6b2b933f7fb5dd1fd6fe7da967f3f22a27c4253c

### CODE REVIEW

**Comment by kuiwang02** [comment]
/hold

it for pre-testing.
thanks

**Comment by kuiwang02** [comment]
/unhold

pre-verify pass

**Review by m1kola — APPROVED** [review]
/lgtm

**Pull request merged**
