### PR TITLE
OCPBUGS-948: Set openshift.io/scc label to empty

### PR DESCRIPTION
**Pull request by tmshort**
Label is unused.

### CODE REVIEW

**Comment by tmshort** [comment]
@jianzhangbjz can I get a QE on this?

**Comment by tmshort** [comment]
@awgreene are these failures related to the disruption budget?

**Review by ankitathomas — APPROVED** [review]
/lgtm

**Comment by tmshort** [comment]
Should this go to 4.12? @awgreene ?

**Pull request merged**
