### PR TITLE
OCPBUGS-7910: Sort channels in lexicographical order in Packagemanifest(#2925)

### PR DESCRIPTION
**Pull request by anik120**
See https://github.com/operator-framework/operator-registry/issues/1069 for more details

Upstream-repository: operator-lifecycle-manager
Upstream-commit: e4b15326c297f610dbf569d771abd62a703b0eb2

### CODE REVIEW

**Comment by anik120** [comment]
/hold 

I don't think I pulled in the commit right, I'll get back to this in a bit

**Comment by anik120** [comment]
/hold cancel 

Should be good now

**Comment by tmshort** [comment]
#474 is _trying_ to do a sync from upstream, including this.

**Comment by anik120** [comment]
https://github.com/openshift/operator-framework-olm/pull/474#issuecomment-1476346506

**Pull request closed without merging**
