### PR TITLE
OLM-2690: Subscription affinity

### PR DESCRIPTION
**Pull request by perdasilva**
This PR brings down changes to the Subscription API that allows users to override the pod.spec.affinity of the operator deployment to enable deployment into multi-arch clusters

### CODE REVIEW

**Comment by perdasilva** [comment]
@bandrade any ETA on this one?

**Comment by bandrade** [comment]
@perdasilva @jianzhangbjz I'm working on it. I should finish tomorrow. Sorry for the late response

**Comment by bandrade** [comment]
```
oc exec catalog-operator-5b668f4d9d-f2krm  -n openshift-operator-lifecycle-manager -- olm --version
OLM version: 0.19.0
git commit: c5a0ad3b230f04b5ec47525854fcf306f6250d5c
```

### Testing scenario 1 -  CR with NodeAffinity defined, POD should be scheduled in a specific node

```
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: example
  namespace: test
spec:
  evaluationInterval: 30s
  serviceMonitorSelector: {}
  alerting:
    alertmanagers:
      - namespace: monitoring
        name: alertmanager-main
        port: web
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - values:
                  - ci-ln-9mfwdi2-72292-rw7jx-worker-c-cqwmw
                key: kubernetes.io/hostname
                operator: In
  probeSelector: {}
  podMonitorSelector: {}
  scrapeInterval: 30s
  ruleSelector: {}
  replicas: 2
  serviceAccountName: prometheus-k8s

  oc get pods -n test -o wide
  NAME                                   READY   STATUS    RESTARTS   AGE   IP            NODE                                       NOMINATED NODE   READINESS GATES
  prometheus-example-0                   2/2     Running   0          36s   10.131.0.21   ci-ln-9mfwdi2-72292-rw7jx-worker-c-cqwmw   <none>           <none>
  prometheus-example-1                   2/2     Running   0          36s   10.131.0.22   ci-ln-9mfwdi2-72292-rw7jx-worker-c-cqwmw   <none>           <none>
  prometheus-operator-787d8d5fb6-wf7zv   1/1     Running   0          13m   10.131.0.19   ci-ln-9mfwdi2-72292-rw7jx-worker-c-cqwmw   <none>           <none>

```



### Testing scenario 2 -  CR with anti-affinity defined, POD should not be scheduled in a node with a specific label defined.

```
  oc label node ci-ln-9mfwdi2-72292-rw7jx-worker-c-cqwmw app=dev                                                                                                                                                                        
  node/ci-ln-9mfwdi2-72292-rw7jx-worker-c-cqwmw labeled

  apiVersion: monitoring.coreos.com/v1
  kind: Prometheus
  metadata:
    name: example
    namespace: test
  spec:
    evaluationInterval: 30s
    serviceMonitorSelector: {}
    alerting:
      alertmanagers:
        - namespace: monitoring
          name: alertmanager-main
          port: web
    affinity:
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
                - values:
                    - dev
                  key: app
                  operator: In
            topologyKey: kubernetes.io/hostname
    probeSelector: {}
    podMonitorSelector: {}
    scrapeInterval: 30s
    ruleSelector: {}
    replicas: 2
    serviceAccountName: prometheus-k8s

  oc get pods -n test -o wide
   NAME                                   READY   STATUS    RESTARTS   AGE   IP            NODE                                       NOMINATED NODE   READINESS GATES
   prometheus-example-0                   2/2     Running   0          30s   10.131.0.29   ci-ln-9mfwdi2-72292-rw7jx-worker-c-cqwmw   <none>           <none>
   prometheus-example-1                   2/2     Running   0          30s   10.128.2.14   ci-ln-9mfwdi2-72292-rw7jx-worker-b-6zgrh   <none>           <none>
   prometheus-operator-787d8d5fb6-ft8z4   1/1     Running   0          78s   10.129.2.14   ci-ln-9mfwdi2-72292-rw7jx-worker-a-vfvnp   <none>           <none>
```

/lgtm

**Pull request merged**
