### PR TITLE
Bug 1961459: add CatalogSource info

### PR DESCRIPTION
**Pull request by jianzhangbjz**
It's better to add the `CatalogSource` info to the event so that the users don't need to check the `subscription`.
Current:
```yaml
no operators found with name etcdoperator.v0.9.3 in channel singlenamespace-alpha of package etcd in the catalog referenced by subscription wrong-test2, subscription wrong-test2 exists
```

### CODE REVIEW

**Comment by benluddy** [comment]
Hey @jianzhangbjz, this looks like a good change. Thanks!

Since this is useful both for upstream operator-framework and OpenShift, please open this PR against https://github.com/operator-framework/operator-lifecycle-manager. It will be pulled downstream for OpenShift 4.9 (or if you think this should be treated as bug in 4.8, we can track it as a low severity 4.8 issue in Bugzilla).

You will also find that several tests need to be updated to expect the new text.

**Comment by jianzhangbjz** [comment]
@benluddy Many thanks for your suggestions! I have created a low priority bug for this PR, and submit another PR(https://github.com/operator-framework/operator-lifecycle-manager/pull/2163) for the upstream.

**Comment by jianzhangbjz** [comment]
Solve:
```yaml
INFO[2021-05-18T02:24:16Z] all modules verified                         
INFO[2021-05-18T02:24:16Z]  .../pkg/controller/registry/resolver/resolver.go                    | 6 +++--- 
INFO[2021-05-18T02:24:16Z]  1 file changed, 3 insertions(+), 3 deletions(-) 
INFO[2021-05-18T02:24:16Z] {"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-05-18T02:24:12Z"} 
INFO[2021-05-18T02:24:16Z]  
```

**Comment by jianzhangbjz** [comment]
UT failures:
```yaml
make[2]: *** [Makefile:50: unit] Error 1
make[2]: Leaving directory '/go/src/github.com/openshift/operator-framework-olm/staging/operator-lifecycle-manager'
make[1]: *** [Makefile:100: unit] Error 2
make[1]: Leaving directory '/go/src/github.com/openshift/operator-framework-olm'
make: *** [Makefile:91: unit/olm] Error 2
{"component":"entrypoint","error":"wrapped process failed: exit status 2","file":"prow/entrypoint/run.go:80","func":"k8s.io/test-infra/prow/entrypoint.Options.Run","level":"error","msg":"Error executing test process","severity":"error","time":"2021-05-18T03:02:25Z"}
```

**Comment by jianzhangbjz** [comment]
According to https://bugzilla.redhat.com/show_bug.cgi?id=1961459#c1, and we have fixed this issue on upstream: https://github.com/operator-framework/operator-lifecycle-manager/blob/master/pkg/controller/registry/resolver/resolver.go#L209-L214 so, close this PR, thanks!
/close

**Pull request closed without merging**
