### PR TITLE
Bug 1983673: Check for pruned bundles on add in replaces mode

### PR DESCRIPTION
**Pull request by ankitathomas**
* check for pruned bundles in replaces-mode add

Signed-off-by: Ankita Thomas <ankithom@redhat.com>

* improve readability, generate testdata

Signed-off-by: Ankita Thomas <ankithom@redhat.com>

Upstream-repository: operator-registry
Upstream-commit: d446d3cf05b2aafccdee8d8b9ea09bbbf4279e28

### CODE REVIEW

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Comment by ankitathomas** [comment]
cherry-pick release-4.8

**Pull request merged**
