### PR TITLE
[release-4.15] OCPBUGS-25798: Deprecation snapshot backport

### PR DESCRIPTION
**Pull request by dtfranz**
Cherry-pick of #654

### CODE REVIEW

**Comment by dtfranz** [comment]
Looks like cluster creation failure.
/retest

**Comment by dtfranz** [comment]
We're running into test flakes now that have yet to be backported. I'll give this one more shot, but otherwise we'll need to wait for that to get this in.
/test e2e-gcp-olm

**Comment by Xia-Zhao-rh** [comment]
test success, detail https://issues.redhat.com/browse/OCPBUGS-25798

**Comment by dtfranz** [comment]
Merged in #670; closing.

**Pull request closed without merging**
