### PR TITLE
[release-4.8] Bug 1996162: Check for pruned bundles on add in replaces mode

### PR DESCRIPTION
**Pull request by ankitathomas**
* check for pruned bundles in replaces-mode add

Signed-off-by: Ankita Thomas <ankithom@redhat.com>

* improve readability, generate testdata

Signed-off-by: Ankita Thomas <ankithom@redhat.com>

Upstream-repository: operator-registry
Upstream-commit: d446d3cf05b2aafccdee8d8b9ea09bbbf4279e28

### CODE REVIEW

**Comment by kevinrizza** [comment]
/lgtm
/hold

holding because apparently tide is just ignoring the valid/invalid bug labels

**Comment by timflannagan** [comment]
/retitle Bug 1996162: Check for pruned bundles on add in replaces mode

**Comment by timflannagan** [comment]
Reads like a flake but continuously happening. Removing the lgtm so the bot doesn't continue to retest while we triage further.

/lgtm cancel

**Comment by Xia-Zhao-rh** [comment]
@ankitathomas Hi, I test it, it is Ok for me. Do you have any plan to add the lgtm label back?

**Pull request merged**
