### PR TITLE
OCPBUGS-31651: [release-4.15] Correctly detect catalog image ID for extractContent catalog pods

### PR DESCRIPTION
**Pull request by joelanford**
Upstream-repository: operator-lifecycle-manager
Upstream-commit: 275d62ee402e1b2b5447aa92ca5a5e8f016e9168

### CODE REVIEW

**Comment by jianzhangbjz** [comment]
That's strange! It should pass, but the test failed! We tested it four times to double confirm this result: https://issues.redhat.com//browse/OCPBUGS-31651 , could you help have a look? Thanks!
/hold

**Review by tmshort — APPROVED** [review]
/lgtm

Assuming tests pass.

**Comment by joelanford** [comment]
label /backport-risk-assessed

**Comment by jianzhangbjz** [comment]
Retest it and pass, details: https://issues.redhat.com/browse/OCPBUGS-31651
/lgtm
/label qe-approved
/label cherry-pick-approved

**Pull request merged**
