### PR TITLE
OCPBUGS-20400: Add OLMConfig API to control package server sync interval [release-4.14]

### PR DESCRIPTION
**Pull request by tmshort**
Also changes the default sync interval _within_ the package server to `12h`, but the package server manager still initializes it to `5m` via the containers command arguments. The OLMConfig `.spec.features.packageServerSyncInterval` will override that value dynamically.

### CODE REVIEW

**Comment by tmshort** [comment]
Removed OCPBUGS-17950 from the title.

**Comment by jianzhangbjz** [comment]
Test pass, detials: https://issues.redhat.com//browse/OCPBUGS-20400
image
image
/label qe-approved
/lgtm

**Comment by tmshort** [comment]
ping @jianzhangbjz for (cherry-pick-approved)

**Pull request merged**
