### PR TITLE
Subscription affinity api

### PR DESCRIPTION
**Pull request by perdasilva**
Adds Subscription spec.config.affinity to allow users to configure workload scheduling against heterogeneous clusters (e.g. on arm64 nodes)

### CODE REVIEW

**Comment by grokspawn** [comment]
This [CI error](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_operator-framework-olm/353/pull-ci-openshift-operator-framework-olm-master-e2e-gcp/1557338517464420352) looks legit.

**Comment by perdasilva** [comment]
closing this in favor of: https://github.com/openshift/operator-framework-olm/pull/352

**Pull request closed without merging**
