### PR TITLE
Bug 1949294: fix environment variable merging from subscription.config

### PR DESCRIPTION
**Pull request by joelanford**
Downstream port of https://github.com/operator-framework/operator-lifecycle-manager/pull/2098

### CODE REVIEW

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Review by timflannagan — COMMENTED** [review]
You need to also run `make vendor` at the root so the changes made to the staging repositories are added to the root vendor tree.

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Comment by timflannagan** [comment]
/retest

```
failed to acquire lease: resources not found
--
```

**Comment by jmazzitelli** [comment]
Just FYI: I provided my test case as a comment in the BZ: https://bugzilla.redhat.com/show_bug.cgi?id=1949294#c6

I mention this because my use-case was not fixed by the stated workaround in that BZ - so it is possible what I am seeing is different and may or may not be fixed by this PR.

**Pull request merged**
