### PR TITLE
OCPBUGS-36661,OCPBUGS-37819: Synchronize From Upstream Repositories

### PR DESCRIPTION
**Pull request by perdasilva**
Fixes #847

### CODE REVIEW

**Comment by jianzhangbjz** [comment]
Pre-merge test pass, details: https://issues.redhat.com/browse/OCPBUGS-36661
/lgtm
/label qe-approved

**Comment by anik120** [comment]
/retitle OCPBUGS-36661: Synchronize From Upstream Repositories

**Comment by grokspawn** [comment]
/retitle OCPBUGS-36661,OCPBUGS-37819: Synchronize From Upstream Repositories

**Comment by grokspawn** [comment]
/retitle OCPBUGS-36661,OCPBUGS-37819: Synchronize From Upstream Repositories

**Pull request merged**
