### PR TITLE
OCPBUGS-4955: Set ImagePullPolicy of bundle unpacker to "IfNotPresent" for image digests

### PR DESCRIPTION
**Pull request by dtfranz**
Allows users to set an image pull policy of "IfNotPresent" for bundle unpacker by specifying an image digest.

### CODE REVIEW

**Comment by jianzhangbjz** [comment]
Test fail, details: https://issues.redhat.com/browse/OCPBUGS-4955
/hold

**Comment by dtfranz** [comment]
> Test fail, details: https://issues.redhat.com/browse/OCPBUGS-4955 /hold

Hi @jianzhangbjz , please re-test when you can. I've updated the branch and I believe your test should now pass.

**Comment by jianzhangbjz** [comment]
LGTM, details: https://issues.redhat.com/browse/OCPBUGS-4955 
/lgtm
/label qe-approved

**Pull request merged**
