### PR TITLE
OCPBUGS-650: fixing reliance on candidate channel containing all referenced bundle…

### PR DESCRIPTION
**Pull request by grokspawn**
…s (#1009)

Signed-off-by: Jordan Keister <jordan@nimblewidget.com>
Upstream-commit: 52e35f0291529290363e0e2d23d5b0c1524103c1
Upstream-repository: operator-registry

### CODE REVIEW

**Review by timflannagan — APPROVED** [review]

**Comment by grokspawn** [comment]
Dangit. That's related to the pipe support for semver veneer that we had.  I had seen that error before, but I thought it was fixed.  If you open a bug for that I can get them to investigate.

**Comment by Xia-Zhao-rh** [comment]
@grokspawn Thanks a lot. I create a bug https://issues.redhat.com/browse/OCPBUGS-1004 to track that problem.

**Pull request merged**
