### PR TITLE
OCPBUGS-17157: manifests: add $GOMEMLIMIT to PSM

### PR DESCRIPTION
**Pull request by stevekuznetsov**
This component has inuse_space around 3MiB in the wild.

### CODE REVIEW

**Comment by stevekuznetsov** [comment]
Screenshot from 2023-08-21 09-32-41

We are in likely the best state we can be, unless I figure out what is going on with GCSys ...

**Review by awgreene — APPROVED** [review]
/approve

**Review by tmshort — APPROVED** [review]
/lgtm

**Comment by perdasilva** [comment]
@stevekuznetsov I think the CI failure is legitimate:

```
Expected
    <[]error | len:1, cap:1>: [
        <*errors.errorString | 0xc0020632c0>{
            s: "following target does not secure metrics endpoint: openshift-operator-lifecycle-manager/package-server-manager",
        },
    ]
to be empty
```

we may need to investigate further

**Pull request merged**
