### PR TITLE
OCPBUGS-41549:  [4.17] adds paginating lister for evaluating CRs' upgrade fitness versus new CRDs.

### PR DESCRIPTION
**Pull request by grokspawn**
…  (#3387)

* paging lister for CRDs
* review resolutions
---------
Upstream-repository: operator-lifecycle-manager
Upstream-commit: 48a856ab0972be8d421b454b854db117975f5cca

### CODE REVIEW

**Comment by jianzhangbjz** [comment]
Test pass, details: https://issues.redhat.com/browse/OCPBUGS-41549
/lgtm
/label qe-approved
/label cherry-pick-approved

**Comment by grokspawn** [comment]
/cherry-pick release-4.16,release-4.15,release-4.14,release-4.13,release-4.12

**Comment by grokspawn** [comment]
/cherrypick release-4.16 release-4.15 release-4.14 release-4.13 release-4.12

**Pull request merged**
