### PR TITLE
Skuznets/bump upstream

### PR DESCRIPTION
**Pull request by stevekuznetsov**

### CODE REVIEW

**Comment by tmshort** [comment]
@dinhxuanvu Hmmm...  It passes upstream, and I had my stuff downstreamed for testing in #570 and #571, where those changes successfully passed the e2es. So, not sure what's happening. I _did_ see some of the original e2e's failing because we couldn't deploy on EC2.

**Comment by tmshort** [comment]
@dinhxuanvu I think I know what's going on... and it's due to the combination of #570 and #571 not being tested _together_.

Downstream sets a value via the CLI, which effectively changes the default value; and that isn't handled properly.

**Comment by dinhxuanvu** [comment]
> @dinhxuanvu I think I know what's going on... and it's due to the combination of #570 and #571 not being tested _together_.
> 
> Downstream sets a value via the CLI, which effectively changes the default value; and that isn't handled properly.

I see. Just a reminder is that ClusterOperator API is a downstream API (OpenShift specific) so this type of problems usually won’t surface on upstream.

**Comment by dinhxuanvu** [comment]
Let put a hold here until Todd resolves this issue fully.
/hold

**Comment by tmshort** [comment]
>I see. Just a reminder is that ClusterOperator status is a downstream API (OpenShift specific) so this type of problems usually won’t surface on upstream.

It was packageserver, which is an upstream component, that's crash looping.

**Comment by dinhxuanvu** [comment]
> > I see. Just a reminder is that ClusterOperator status is a downstream API (OpenShift specific) so this type of problems usually won’t surface on upstream.
> 
> It was packageserver, which is an upstream component, that's crash looping.

Yes the component in trouble was packageserver but the error that blocked the test was from ClusterOperator API which reported packageserver was not ready.

**Comment by dinhxuanvu** [comment]
> But if packageserver wasn't crashing in the first place....
> 
> But, packageserver has been fixed upstream, so @stevekuznetsov should re-run the script.

Haha. I wasn't contradicting you on the root cause, only on the way the error surfaced up.
Anyway, the issue should be resolved now so rebase this PR and continue.

**Comment by tmshort** [comment]
See #573

**Pull request closed without merging**
