### PR TITLE
Sync registry 12-16

### PR DESCRIPTION
**Pull request by anik120**

### CODE REVIEW

**Comment by dinhxuanvu** [comment]
@anik120 This PR fails verify for some reason.

**Comment by ankitathomas** [comment]
> @anik120 This PR fails verify for some reason.

The .gitignore commit doesn't have the Upstream-repository/commit trailers, either that commit needs to be taken out/amended or that check needs to be turned off

**Comment by anik120** [comment]
@ankitathomas @dinhxuanvu I've dropped the `.gitignore` commit, that commit is in fact not needed in this repo. Should be good to go now.

**Comment by timflannagan** [comment]
This didn't make the feature freeze cut

/hold

**Comment by timflannagan** [comment]
I think we can close this out now that we're past feature freeze unless we want to market this as a bug and attach a BZ # to this PR.

/close

**Pull request closed without merging**
