### PR TITLE
OCPBUGS-4799: Fix label key truncation for subscription annotations (#2731)

### PR DESCRIPTION
**Pull request by grokspawn**
Signed-off-by: Per Goncalves da Silva <pegoncal@redhat.com>

Co-authored-by: Per Goncalves da Silva <pegoncal@redhat.com>
Upstream-repository: operator-lifecycle-manager
Upstream-commit: 1bdf969e6dff317e975de21078d60dd1406235e0

### CODE REVIEW

**Comment by jianzhangbjz** [comment]
I guess it needs the `/approve` label.
/assign @gallettilance @perdasilva @grokspawn

**Comment by grokspawn** [comment]
> I guess it needs the `/approve` label. /assign @gallettilance @perdasilva @grokspawn

It was strange that it retracted the approved label once Bruno applied the cherry-pick-approved label.  Is that intentional?

**Pull request merged**
