### PR TITLE
OCPBUGS-1004: dump descriptive source info on error instead of the source data (#1021)

### PR DESCRIPTION
**Pull request by grokspawn**
Signed-off-by: Jordan Keister <jordan@nimblewidget.com>
Upstream-commit: a3c883e9beee343bd55fd73c1447ea5e98459951
Upstream-repository: operator-registry

### CODE REVIEW

**Comment by grokspawn** [comment]
/hold cancel 
got qe-approved label

**Review by timflannagan — APPROVED** [review]

**Review by dinhxuanvu — APPROVED** [review]
/lgtm

**Pull request merged**
