### PR TITLE
[release-4.12] OCPBUGS-42161: adds paginating lister for evaluating CRs' upgrade fitness versus new CRDs

### PR DESCRIPTION
**Pull request by perdasilva**
Manual backport of #871 to get CI rolling and hopefully merge it down quick(er)

### CODE REVIEW

**Comment by jianzhangbjz** [comment]
Test pass, details: https://issues.redhat.com/browse/OCPBUGS-42161
 However, there is an instant issue: `The provided continue parameter is too old to display a consistent list result`, so I /hold this PR. Please feel free to /unhold it if this is not an issue.
```console
  message: 'retrying execution due to error: error validating existing CRs against
    new CRD''s schema for "applications.argoproj.io": The provided continue parameter
    is too old to display a consistent list result. You can start a new list without
    the continue parameter, or use the continue token in this response to retrieve
    the remainder of the results. Continuing with the provided token results in an
    inconsistent list - objects that were created, modified, or deleted between the
    time the first chunk was returned and now may show up in the list.'
```
/lgtm
/label qe-approved
/label cherry-pick-approved
/hold

**Comment by perdasilva** [comment]
@jianzhangbjz Thank you!!! I'll :eyes: the issue and see what's up

**Comment by perdasilva** [comment]
The flaky test is failing due to the Eventually timeout competing with the InstallPlan retry time out. Testing this PR on cluster bot, I increased the Eventually timeout and got the test to consistently pass (> 30 times SUCCESS every time)

**Pull request merged**
