### PR TITLE
OCPBUGS-30219: bump otelgrpc to 0.46.0

### PR DESCRIPTION
**Pull request by grokspawn**
Manual backport cherry-pick of https://github.com/openshift/operator-framework-olm/pull/712/commits/e2e482af7d8fbb9ec0ae8af49eb318120090d53e

### CODE REVIEW

**Review by everettraven — APPROVED** [review]
/lgtm

**Comment by emmajiafan** [comment]
The otelgrpc is still 0.44.0: https://github.com/openshift/operator-framework-olm/pull/712/files#diff-a5e215633ff8e6a4eabb33ba5583967629ba72422d56e9881b3eee83aab1f212L206

**Comment by grokspawn** [comment]
good spot, @emmajiafan.  Updated, pending ci.

**Review by everettraven — APPROVED** [review]
/lgtm

**Pull request merged**
