### PR TITLE
Bug 2101357: concurrent write bug fix

### PR DESCRIPTION
**Pull request by perdasilva**
* Update catalog source pod creation to not mutate parameters

Signed-off-by: perdasilva <perdasilva@redhat.com>

* Update pkg/controller/registry/reconciler/reconciler_test.go

Co-authored-by: Alexander Greene <agreene@redhat.com>
Signed-off-by: perdasilva <perdasilva@redhat.com>

Co-authored-by: Alexander Greene <agreene@redhat.com>
Upstream-repository: operator-lifecycle-manager
Upstream-commit: 83e3ebf96856643286e2e3e9438352c975923858

### CODE REVIEW

**Review by exdx — APPROVED** [review]
/lgtm

**Comment by perdasilva** [comment]
Note: we'll have to backport to 4.11

**Comment by jianzhangbjz** [comment]
Looks good to me, details: https://bugzilla.redhat.com/show_bug.cgi?id=2101357#c10
/label qe-approved
/lgtm

**Pull request merged**
