### PR TITLE
OCPBUGS-35970: add io.openshift.release.operator label to image

### PR DESCRIPTION
**Pull request by Ximinhan**
we want to make the image shows up in release payload
Ref https://docs.ci.openshift.org/docs/how-tos/onboarding-a-new-component/#product-builds-and-becoming-part-of-an-openshift-release

### CODE REVIEW

**Comment by perdasilva** [comment]
/title NO-ISSUE: add io.openshift.release.operator label to image

**Comment by grokspawn** [comment]
/retitle OCPBUGS-35970: add io.openshift.release.operator label to image

**Pull request merged**
