### PR TITLE
OPRUN-2913: Sync from api repo 1

### PR DESCRIPTION
**Pull request by tmshort**
This syncs two commits from the upstream `api` repo. Additional PRs will be opened for the rest of the api, operator-lifecycle-manager and operator-registry upstream repos.

### CODE REVIEW

**Comment by tmshort** [comment]
Everything passed! But I need approvals, LGTM and other labels. @anik120

**Comment by grokspawn** [comment]
/lgmt 
but don't we need a jira for this?

**Comment by grokspawn** [comment]
/lgmt 
but don't we need a jira for this?

**Comment by tmshort** [comment]
There's no jira ticket associated with either of the upstream commits.

**Comment by tmshort** [comment]
@grokspawn Is there a way to override (Jira) or could @joelanford merge it?

**Comment by grokspawn** [comment]
> @grokspawn Is there a way to override (Jira) or could @joelanford merge it?

Joe might be able to merge it, but I was pretty sure that the downstream process required a jira/BZ tracking vehicle.  
@awgreene may be able to give context here.

**Pull request closed without merging**
