### PR TITLE
OPRUN-3063: Microshift manifests remove collection-profiles cronjob from kustomization

### PR DESCRIPTION
**Pull request by jmprusi**
Removes the collect profiles cronjob from the microshift kustomization.yaml file.

### CODE REVIEW

**Comment by grokspawn** [comment]
Could you retitle your commit messages to include the `UPSTREAM: <carry>: ` prefix so we know to keep them when we downstream add'l feature content?

**Review by awgreene — APPROVED** [review]
/lgtm

**Review by m1kola — APPROVED** [review]
/lgtm

**Review by m1kola — APPROVED** [review]
/lgtm

**Pull request merged**
