### PR TITLE
OCPBUGS-30775: [4.14] bump grpc to 1.60.1, reconnect idle connections (#3147)

### PR DESCRIPTION
**Pull request by grokspawn**
Upstream-repository: operator-lifecycle-manager
Upstream-commit: e6d8fb022872af61bd34e80c185ff206d01dabcf

### CODE REVIEW

**Review by everettraven — APPROVED** [review]
/lgtm

**Review by tmshort — APPROVED** [review]
/lgtm

**Review by KeenonLee — COMMENTED** [review]
/label cherry-pick-approved

**Pull request merged**
