### PR TITLE
Sync 0307

### PR DESCRIPTION
**Pull request by perdasilva**

### CODE REVIEW

**Comment by everettraven** [comment]
@perdasilva I don't think the `ci/prow/unit-registry` test is going to pass due to some issues with the way the unit tests were configured for the composite template (veneer) in operator-registry. It requires that Docker be present and when @grokspawn attempted to downstream the veneer --> template rename (https://github.com/openshift/operator-framework-olm/pull/461) we weren't able to get it to work because the prow environment doesn't have Docker installed.

We are currently working on making some changes to the composite template upstream in https://github.com/operator-framework/operator-registry/pull/1075 to fix this issue and enable us to properly downstream commits made after the addition of the composite template.

**Comment by tmshort** [comment]
Any updates on this?

**Comment by perdasilva** [comment]
@tmshort I didn't get a chance to finish looking into this. I'm happy to close this if you want to take over with your work. I just wanted to get some idea of how far behind we are =S

**Comment by tmshort** [comment]
> @tmshort I didn't get a chance to finish looking into this. I'm happy to close this if you want to take over with your work. I just wanted to get some idea of how far behind we are =S

You got further ahead than I did... this is a better starting point, but everything is failing...

**Comment by grokspawn** [comment]
> @tmshort  Any updates on this?

Just merged.  We were blocked by the org-wide CI issue. :(

**Comment by perdasilva** [comment]
closing as this is out of date and todd is on it!

**Pull request closed without merging**
